from app.main import (
    auth_bp, admin_bp, teacher_bp, student_bp, parent_bp,
    settings_bp, classes_bp, school_bp, subjects_bp, employees_bp,
    students_bp, guardians_bp, timetables_bp, fees_bp, accounts_bp,
    payroll_bp, attendance_bp, question_bank_bp, examination_bp,
    reports_bp, certificates_bp, notices_bp, circulars_bp,
    communication_bp, syllabus_bp, syllabus_monitoring_bp,
    ai_insights_bp, messaging_bp, notifications_bp, store_bp,
    homework_bp, behaviour_skills_bp
)

__all__ = [
    'auth_bp', 
    'admin_bp', 
    'teacher_bp', 
    'student_bp', 
    'parent_bp',
    'settings_bp', 
    'classes_bp', 
    'school_bp',
    'subjects_bp',
    'employees_bp',
    'students_bp',
    'guardians_bp',
    'timetables_bp',
    'fees_bp',
    'accounts_bp',
    'payroll_bp',
    'attendance_bp',
    'question_bank_bp',
    'examination_bp',
    'reports_bp',
    'certificates_bp',
    'notices_bp',
    'circulars_bp',
    'communication_bp',
    'syllabus_bp',
    'syllabus_monitoring_bp',
    'ai_insights_bp'
]
